@startuml product inventory

    entity roles {
        * role VARCHAR(50) <<PK>>
        --
    }

    entity users {
        * id INT(10) <<PK>>
        --
        * name VARCHAR(100)
        * email VARCHAR(100) <<unique>>
        * password VARCHAR(256)
          phone_number VARCHAR(15)
          role VARCHAR(50) <<FK>>
          created_at TIMESTAMP NULL
          updated_at TIMESTAMP CURRENT_TIMESTAMP
    }

    entity categories {
        * category VARCHAR(256) <<PK>>
    }

    entity products {
        * id VARCHAR(25) <<PK>> uniqid()
        --
        * name VARCHAR(100)
          category VARCHAR(256) <<FK>>
          price INT(11) UNSIGNED 0
          stock INT(11) UNSIGNED 0
          attachment VARCHAR(255) 
          admin_email VARCHAR(100) <<FK>>
          created_at TIMESTAMP NULL
          updated_at TIMESTAMP CURRENT_TIMESTAMP
    }

   roles }|--|| users : have
   categories }|--|| products : have
   users ||--|| products : inserted by

@enduml